### ISSUE TITLE
Add learning resources in README section

### ISSUE THREAD

**Issue by codeclassifiers** [codeclassifiers/react30_5_image_gallery_app#2]
Add learning resources in README.md section related to how to make API calls in react.js components and building a responsive website using a bootstrap grid layout.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred

**Comment by bineetNaidu** [comment]
Once again i would like contribute on this issue and feel free to assign me this task.

**Comment by ZsuzsaMano** [comment]
I have some great tutorial links to share. Please assign me

**Comment by SriCoD** [comment]
i can work well on this

**Comment by codeclassifiers** [comment]
@ZsuzsaMano and @SriCoD You have been added as assignees. Feel free to contribute to this repository.

**Comment by codeclassifiers** [comment]
@bineetNaidu You have been added as assignee. Please follow Markdown syntax while submitting learning resources.

**Comment by LondonTran** [comment]
Hi I would like to work on this.

**Comment by codeclassifiers** [comment]
@LondonTran You have been added as assignee. Please follow Markdown syntax while submitting learning resources.

**Comment by LondonTran** [comment]
Hi @codeclassifiers I submitted a PR #12 :)

**Comment by codeclassifiers** [comment]
@LondonTran Your pull request is merged with relevant Hacktoberfest labels. Thank you for your contributions to this repository.

**Comment by LondonTran** [comment]
Thank you!
