### ISSUE TITLE
Build your own variation of Image gallery

### ISSUE THREAD

**Issue by codeclassifiers** [codeclassifiers/react30_5_image_gallery_app#3]
Modify the CSS or the base code to build your own version of the image gallery.
Submissions by multiple contributors to this issue are allowed.
Steps to contribute:
1. Comment on this issue if you are interested in building your own version
2. Wait for being assigned to the issue and getting solution number
3. Once solution number is assigned, clone the repository and create a folder `solution_[your_assigned_number]` in the repo.
    For example, if `solution_3` is assigned to you then you need to create a folder `solution_3` in this repo.
4. If you are a beginner who would only like to modify CSS then copy the code from `solution_1` folder into your assigned folder. If you know react and want to build your own solution then copy the code from `1_starter_code` into your assigned folder.
5. Once finished submit your solution as pull request to this repository. 

Note: No pull request will be accepted until you are added as an assignee to this issue.

**Comment by ddaniss** [comment]
I'd like to try

**Comment by ellu-laitinen** [comment]
I'd like to do this!

**Comment by ZsuzsaMano** [comment]
HI, 

I would like to do this

**Comment by SriCoD** [comment]
im passionately looking up to work on this project

**Comment by codeclassifiers** [comment]
@ellu-laitinen You have been added as contributor. You can submit your version of project in `solution_2` folder.

**Comment by codeclassifiers** [comment]
@ZsuzsaMano You have been added as contributor. You can submit your version of project in `solution_3` folder.

**Comment by codeclassifiers** [comment]
@SriCoD You have been added as contributor. You can submit your version of project in `solution_4` folder.

**Comment by fawad60** [comment]
i will like to work on it

**Comment by techyringo** [comment]
I'd like to do this!

**Comment by ZsuzsaMano** [comment]
The solution_1 is already styled. Can I remove all styles? I think the assignment would make more sense. Or is it on purpose pre-styled? If you wanna get different ideas on how to style a gallery, I think it is better to start it with no style at all.

**Comment by hexifox** [comment]
Hey, I would love to give this a try! :)

**Comment by codeclassifiers** [comment]
@ellu-laitinen and @ZsuzsaMano Your submitted solutions are merged with main branch. Thank you for your contributions to this project.

**Comment by web2feel** [comment]
I would like to submit a gallery variation.

**Comment by LondonTran** [comment]
Hi I would like to work on this.
